In [2]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression() # The model is used in the same way as the LinearRegression class.

In [3]:
import pandas as pd

# we pass 'index_col' to avoid redundancy since "PassengerId" is an index column same as the one pandas adds.
titanic = pd.read_csv("titanic.csv", index_col="PassengerId")

titanic.head() # Inspect the data

             Survived  Pclass  ... Cabin Embarked
PassengerId                    ...
1                   0       3  ...   NaN        S
2                   1       1  ...   C85        C
3                   1       3  ...   NaN        S
4                   1       1  ...  C123        S
5                   0       3  ...   NaN        S

[5 rows x 11 columns]

In [4]:
titanic.info() # get more details of about the dataset

<class 'pandas.core.frame.DataFrame'>
Index: 891 entries, 1 to 891
Data columns (total 11 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Survived  891 non-null    int64
 1   Pclass    891 non-null    int64
 2   Name      891 non-null    object
 3   Sex       891 non-null    object
 4   Age       714 non-null    float64
 5   SibSp     891 non-null    int64
 6   Parch     891 non-null    int64
 7   Ticket    891 non-null    object
 8   Fare      891 non-null    float64
 9   Cabin     204 non-null    object
 10  Embarked  889 non-null    object
dtypes: float64(2), int64(4), object(5)
memory usage: 83.5+ KB

In [5]:
# first we will handle the 'Age' column
titanic.Age.describe()

count    714.000000
mean      29.699118
std       14.526497
min        0.420000
25%       20.125000
50%       28.000000
75%       38.000000
max       80.000000
Name: Age, dtype: float64

In [6]:
# We can the min value being a fraction, this probably means this person was a newborn.
# Let's confirm this by seeing if they had any relatives
titanic[titanic.Age < 1] # Our assumption was correct they all have a relative on board with them.

             Survived  Pclass  ...    Cabin Embarked
PassengerId                    ...
79                  1       2  ...      NaN        S
306                 1       1  ...  C22 C26        S
470                 1       3  ...      NaN        C
645                 1       3  ...      NaN        C
756                 1       2  ...      NaN        S
804                 1       3  ...      NaN        C
832                 1       2  ...      NaN        S

[7 rows x 11 columns]

In [7]:
# What about the 'NaN' ones?
titanic[titanic.Age.isna()] # they seem to be randomly missing values.

             Survived  Pclass  ... Cabin Embarked
PassengerId                    ...
6                   0       3  ...   NaN        Q
18                  1       2  ...   NaN        S
20                  1       3  ...   NaN        C
27                  0       3  ...   NaN        C
29                  1       3  ...   NaN        Q
...               ...     ...  ...   ...      ...
860                 0       3  ...   NaN        C
864                 0       3  ...   NaN        S
869                 0       3  ...   NaN        S
879                 0       3  ...   NaN        S
889                 0       3  ...   NaN        S

[177 rows x 11 columns]

In [8]:
# in this case we could remove outlier values and calculate a mean to fill in the values.
# We will use the IQR method we used in the previous session.
q1 = titanic.Age.quantile(0.25)
q3 = titanic.Age.quantile(0.75)

iqr = q3 - q1

lower_bound = q1 - 1.5 * iqr
upper_bound = q3 + 1.5 * iqr

print(f"Lower Bound: {lower_bound}")
print(f"Upper Bound: {upper_bound}")

# get the values that are greater than the lower bound and lower than the upper bound
in_range_filter = (titanic.Age > lower_bound) & (titanic.Age < upper_bound)
titanic[in_range_filter]

Lower Bound: -6.6875
Upper Bound: 64.8125

             Survived  Pclass  ... Cabin Embarked
PassengerId                    ...
1                   0       3  ...   NaN        S
2                   1       1  ...   C85        C
3                   1       3  ...   NaN        S
4                   1       1  ...  C123        S
5                   0       3  ...   NaN        S
...               ...     ...  ...   ...      ...
886                 0       3  ...   NaN        Q
887                 0       2  ...   NaN        S
888                 1       1  ...   B42        S
890                 1       1  ...  C148        C
891                 0       3  ...   NaN        Q

[703 rows x 11 columns]

In [9]:
# Calculate the mean
age_mean = titanic[in_range_filter].Age.mean()

# fill the missing values, use this method in this way to avoid a deprecation warning.
titanic.fillna({"Age" : age_mean}, inplace=True)

In [10]:
# Let's the check Age column now
titanic.Age.describe()

count    891.000000
mean      29.574554
std       13.004425
min        0.420000
25%       22.000000
50%       29.072077
75%       35.000000
max       80.000000
Name: Age, dtype: float64

In [11]:
# next we will handle the 'Cabin' column
titanic.Cabin.describe() # this column represents the cabin (part of the ship) the passenger was on.

count     204
unique    147
top        G6
freq        4
Name: Cabin, dtype: object

In [12]:
titanic.Cabin.value_counts() # let's check the most common values

Cabin
G6             4
C23 C25 C27    4
B96 B98        4
F2             3
D              3
              ..
E17            1
A24            1
C50            1
B42            1
C148           1
Name: count, Length: 147, dtype: int64

In [13]:
# Let's see how many unique values there are
len(titanic.Cabin.unique()) - 1 # take out the 'NaN' value

147

In [14]:
# The 'Cabin' column seems to be an annoying column to deal with
# it has too many unique values to one-hot encode it.
# and they are evenly distrbuted so filling the missing values with the most common wouldn't be correct
# thus we will just drop it.

titanic.drop(columns=['Cabin'], inplace=True)

titanic.info()

<class 'pandas.core.frame.DataFrame'>
Index: 891 entries, 1 to 891
Data columns (total 10 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Survived  891 non-null    int64
 1   Pclass    891 non-null    int64
 2   Name      891 non-null    object
 3   Sex       891 non-null    object
 4   Age       891 non-null    float64
 5   SibSp     891 non-null    int64
 6   Parch     891 non-null    int64
 7   Ticket    891 non-null    object
 8   Fare      891 non-null    float64
 9   Embarked  889 non-null    object
dtypes: float64(2), int64(4), object(4)
memory usage: 76.6+ KB

In [15]:
# lastly the 'Embarked' column is missing exactly 2 values
titanic[titanic.Embarked.isna()]

             Survived  Pclass  ...  Fare Embarked
PassengerId                    ...
62                  1       1  ...  80.0      NaN
830                 1       1  ...  80.0      NaN

[2 rows x 10 columns]

In [16]:
# Let's check the unique values in the column
titanic.Embarked.unique()

array(['S', 'C', 'Q', nan], dtype=object)

In [17]:
# the most common values
titanic.Embarked.value_counts()

Embarked
S    644
C    168
Q     77
Name: count, dtype: int64

In [18]:
# we can simply drop these two as well or fill in with the most common value as well.
# both are viable options so we will leave them here:

# in this case we will not keep the 2 rows
# titanic.fillna({"Embarked":titanic.Embarked.mode()}, inplace=True)

# Use "subset" argument to determine on which columns to look for missing values
titanic.dropna(subset=['Embarked'], inplace=True)

In [19]:
# Next we'll encode the column

embarked = titanic.pop("Embarked")

embarked_one_hot_encoded = pd.get_dummies(embarked)

embarked_one_hot_encoded.head()

                 C      Q      S
PassengerId
1            False  False   True
2             True  False  False
3            False  False   True
4            False  False   True
5            False  False   True

In [20]:
# then, simply join them back

cleaned_titanic = pd.concat([embarked_one_hot_encoded, titanic], axis=1)

cleaned_titanic.head()

                 C      Q      S  ...  Parch            Ticket     Fare
PassengerId                       ...
1            False  False   True  ...      0         A/5 21171   7.2500
2             True  False  False  ...      0          PC 17599  71.2833
3            False  False   True  ...      0  STON/O2. 3101282   7.9250
4            False  False   True  ...      0            113803  53.1000
5            False  False   True  ...      0            373450   8.0500

[5 rows x 12 columns]

In [21]:
# since the 'Name' column doesn't realy tell the model anything useful and has all unique values we will drop it as well
cleaned_titanic.drop(columns=["Name"], inplace=True)

cleaned_titanic.info()

<class 'pandas.core.frame.DataFrame'>
Index: 889 entries, 1 to 891
Data columns (total 11 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   C         889 non-null    bool
 1   Q         889 non-null    bool
 2   S         889 non-null    bool
 3   Survived  889 non-null    int64
 4   Pclass    889 non-null    int64
 5   Sex       889 non-null    object
 6   Age       889 non-null    float64
 7   SibSp     889 non-null    int64
 8   Parch     889 non-null    int64
 9   Ticket    889 non-null    object
 10  Fare      889 non-null    float64
dtypes: bool(3), float64(2), int64(4), object(2)
memory usage: 65.1+ KB

In [22]:
# the 'Sex' column has 2 possible values, so it can be easliy one-hot encoded

# first we pop it
sex_column = cleaned_titanic.pop("Sex")

# then encode it
sex_one_hot_encoded = pd.get_dummies(sex_column)

sex_one_hot_encoded.head()

             female   male
PassengerId
1             False   True
2              True  False
3              True  False
4              True  False
5             False   True

In [23]:
# Then we add back the column in encoded form

final_titanic = pd.concat([sex_one_hot_encoded, cleaned_titanic], axis=1)

final_titanic.head()

             female   male      C  ...  Parch            Ticket     Fare
PassengerId                        ...
1             False   True  False  ...      0         A/5 21171   7.2500
2              True  False   True  ...      0          PC 17599  71.2833
3              True  False  False  ...      0  STON/O2. 3101282   7.9250
4              True  False  False  ...      0            113803  53.1000
5             False   True  False  ...      0            373450   8.0500

[5 rows x 12 columns]

In [24]:
# Next, the ticket column
final_titanic.Ticket.describe()

count          889
unique         680
top       CA. 2343
freq             7
Name: Ticket, dtype: object

In [25]:
# since it also doesn't entail any useful info, and is similarly hard to deal with like the cabin column
# we'll drop it

final_titanic.drop(columns=['Ticket'], inplace=True)

final_titanic.info()

<class 'pandas.core.frame.DataFrame'>
Index: 889 entries, 1 to 891
Data columns (total 11 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   female    889 non-null    bool
 1   male      889 non-null    bool
 2   C         889 non-null    bool
 3   Q         889 non-null    bool
 4   S         889 non-null    bool
 5   Survived  889 non-null    int64
 6   Pclass    889 non-null    int64
 7   Age       889 non-null    float64
 8   SibSp     889 non-null    int64
 9   Parch     889 non-null    int64
 10  Fare      889 non-null    float64
dtypes: bool(5), float64(2), int64(4)
memory usage: 53.0 KB

In [26]:
final_titanic.head()

             female   male      C      Q  ...   Age  SibSp  Parch     Fare
PassengerId                               ...
1             False   True  False  False  ...  22.0      1      0   7.2500
2              True  False   True  False  ...  38.0      1      0  71.2833
3              True  False  False  False  ...  26.0      0      0   7.9250
4              True  False  False  False  ...  35.0      1      0  53.1000
5             False   True  False  False  ...  35.0      0      0   8.0500

[5 rows x 11 columns]

In [27]:
y = final_titanic.pop("Survived") # this is the value we want to predict.

X = final_titanic # all other columns are input to out model.

X.shape, y.shape

((889, 10), (889,))

In [28]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2) # We will use the same test size as last time.

print(f"Train dataset shapes: {X_train.shape, y_train.shape}") 
print(f"Test dataset shapes: {X_test.shape, y_test.shape}")

Train dataset shapes: ((711, 10), (711,))
Test dataset shapes: ((178, 10), (178,))

In [29]:
# Then we use the same model we instantiated 

model.fit(X_train, y_train) # ignore the warning for now

/home/Mahmoud/Code/Enter-Team-AI-Course/env/lib/python3.13/site-packages/sklearn/linear_model/_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [30]:
# predict on the test data

y_pred = model.predict(X_test)

In [31]:
from sklearn.metrics import accuracy_score

# we use it the same way we did with "MSE" (mean squared error) and "MAE" (mean absolute error)
accuracy = accuracy_score(y_test, y_pred)
print(f"We got: {accuracy*100:.2f}% right!")

We got: 83.15% right!

In [32]:
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors=5) # 'n_neighbors' argument represents the 'K' we discussed

In [33]:
knn.fit(X_train, y_train) # we call the same '.fit()' method.

knn_y_pred = knn.predict(X_test) # Same with the '.predict()' method.

In [34]:
knn_accuracy = accuracy_score(y_test, knn_y_pred)
print(f"We got: {knn_accuracy*100:.2f}% right!")

We got: 71.35% right!